// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_gceSelenium is a generated GoMock package.
package mock_gceSelenium

import (
	gomock "github.com/golang/mock/gomock"
	selenium "github.com/tebeka/selenium"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleSeleniumError mocks base method
func (m *MockService) HandleSeleniumError(internal bool, err error) {
	m.ctrl.Call(m, "HandleSeleniumError", internal, err)
}

// HandleSeleniumError indicates an expected call of HandleSeleniumError
func (mr *MockServiceMockRecorder) HandleSeleniumError(internal, err interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSeleniumError", reflect.TypeOf((*MockService)(nil).HandleSeleniumError), internal, err)
}

// NewClient mocks base method
func (m *MockService) NewClient() error {
	ret := m.ctrl.Call(m, "NewClient")
	ret0, _ := ret[0].(error)
	return ret0
}

// NewClient indicates an expected call of NewClient
func (mr *MockServiceMockRecorder) NewClient() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockService)(nil).NewClient))
}

// Driver mocks base method
func (m *MockService) Driver() selenium.WebDriver {
	ret := m.ctrl.Call(m, "Driver")
	ret0, _ := ret[0].(selenium.WebDriver)
	return ret0
}

// Driver indicates an expected call of Driver
func (mr *MockServiceMockRecorder) Driver() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Driver", reflect.TypeOf((*MockService)(nil).Driver))
}

// WaitForWaitFor mocks base method
func (m *MockService) WaitForWaitFor() error {
	ret := m.ctrl.Call(m, "WaitForWaitFor")
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForWaitFor indicates an expected call of WaitForWaitFor
func (mr *MockServiceMockRecorder) WaitForWaitFor() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForWaitFor", reflect.TypeOf((*MockService)(nil).WaitForWaitFor))
}
